### ISSUE TITLE
Improve gitlab action integration

### ISSUE THREAD

**Issue by gotbadger** [Bearer/bearer#1353]
When using gitlab we have to map a lot of env vars:

```
bearer:
  image:
    name: bearer/bearer
    entrypoint: [ "" ]
  variables:
    SHA: $CI_COMMIT_SHA
    CURRENT_BRANCH: $CI_COMMIT_REF_NAME
    DEFAULT_BRANCH: $CI_DEFAULT_BRANCH
    ORIGIN_URL: $CI_REPOSITORY_URL
  script: bearer scan .
```

Instead of doing this have the cli fallback to looking for these env vars if they can not be found.
