### ISSUE TITLE
Report is not generated

### ISSUE THREAD

**Issue by willyprayogo26** [Bearer/bearer#1434]
Hi

I have a command to generate the report using gitlab CI:
```
SAST Scan:
  stage: build_test_app
  image:
    name: bearer/bearer
    entrypoint: [""]
  script:
    - mkdir sast
    - bearer scan . --format html --output sast/index.html && ls
    - ls -R
  artifacts:
    paths:
      - sast/
    expire_in: 30 mins
  allow_failure: true
  only:
    - uat
```

last time, it works, but now doesn't work
so the pipeline successfully, but the report is not exist or not generated
can u help me for this? what the issue?

Thanks
