### ISSUE TITLE
HTML report date has incorrect ordinal

### ISSUE THREAD

**Issue by sjwarner-bv** [Bearer/bearer#1602]
## Description & Reproduction

The date at the top of the HTML report has an incorrect ordinal. It seems to always be `nd` - which should only be for the 2nd, 22nd of the month.

I run the report in a GitLab CI pipeline as so:

```
diff-security-audit:
  stage: diff-security-audit
  image:
    name: bearer/bearer
    entrypoint: [ "" ]
  script: BEARER_DIFF_BASE_BRANCH=master bearer scan --diff . --format html --output report.html
  artifacts:
    expire_in: 3 days
    paths:
      - report.html
```

See screenshots for incorrect ordinals:

<img width="321" alt="Screenshot 2024-05-17 at 09 49 42" src="https://github.com/Bearer/bearer/assets/92582184/4abd8cc1-4183-425f-b1bd-efd800b37af1">
<img width="326" alt="Screenshot 2024-05-17 at 09 49 49" src="https://github.com/Bearer/bearer/assets/92582184/cbb260cf-1ade-4304-92a7-ed8ba6ac5401">

## Expected Behavior

Expected behaviour: ordinals are correct based on date, or ordinals are not used.

## Actual Behavior

Ordinals are always `nd`

## Possible Fix

I'm not a Go developer, but taken a quick look, and I think:

```
func ReportHTMLWrapper(title string, body *string) (string, error) {
	htmlContent := &strings.Builder{}

	t := time.Now()
	timeLayout := "January 2nd 2006, 15:04:05 pm (MST-0700)"

	wrapperContent := html.WrapperHTMLPage{
		Body:      *body,
		Title:     title,
		TimeStamp: t.Format(timeLayout),
		Style:     strings.Trim(siteCss, ""),
	}
```

in `internal/report/output/html/html.go` might be responsible? From reading: https://stackoverflow.com/questions/55850762/how-to-get-ordinal-indicators-1st-2nd-3rd-etc-in-go there is no built-in support for the time library to use date ordinals. It suggests using the `humanize` library`, or implementing the functionality yourself.

Equally, I think not having ordinals would still be fine, and be much less confusing than `nd` on everything, so adjusting the snippet to use:

`timeLayout := "January 2 2006, 15:04:05 pm (MST-0700)"`

would be fine?

If you are ok with that change, I'd be happy to raise an MR.

## Your Environment

GitLab CI, bearer/bearer Docker image.
