### ISSUE TITLE
Bearer Scan takes very long time

### ISSUE THREAD

**Issue by antonio-ivanovski** [Bearer/bearer#1682]
I am working on monorepo wit fairly small-medium sized project. The scan on CI takes few seconds. However the scan ran locally takes very long time. For initial ran it took ~15 minutes just on `Analyzing codebase` without any timer, then it scanned ~10M files. After that it was taking 2-3m for `Analyzing codebase`.

## Expected Behavior

Runs fast

## Actual Behavior

Runs slow 🤷‍♂️

## Possible Fix

I am suspecting that the `skip-path` is not working as expected

## Your Environment

- Operating System and version: MacOs
- Output of 'bearer version': `bearer version 1.46.1, build 4ef7c0e9a1d2bf2c6c480a38bf13c1f6363af3fd`

This is my config:
```
disable-version-check: false
log-level: info
report:
    fail-on-severity: critical,high,medium,low
    format: ""
    no-color: false
    output: ""
    report: security
    severity: critical,high,medium,low,warning
rule:
    disable-default-rules: false
    only-rule: []
    skip-rule: []
scan:
    context: ""
    data_subject_mapping: ""
    disable-domain-resolution: true
    domain-resolution-timeout: 3s
    exit-code: -1
    external-rule-dir: []
    force: false
    hide_progress_bar: false
    internal-domains: []
    parallel: 0
    quiet: false
    scanner:
        - sast
    skip-path: ['.nx','.local','.output','*/node_modules','*/dist','.github','tools','applications/services/issuer']
    skip-test: true

```

I am running `bearer scan .`
