### ISSUE TITLE
 Can't touch: cannot touch '/Project.tmp/gitlab_runner_env':Permission denied Can't run on default Gitlab CI/CD setting provided in documentation

### ISSUE THREAD

**Issue by a-khash** [Bearer/bearer#1722]
## Description & Reproduction
Ran a Gitlab CI/CD Pipeline with the following configuration: 
Used the following job configuration for Gitlab CI/CD taken from https://docs.bearer.com/guides/gitlab/:
```
bearer:
  image:
    name: bearer/bearer
    entrypoint: [""]
  script:
    - bearer scan . --format gitlab-sast --output gl-sast-report.json
  artifacts:
    reports:
      sast: gl-sast-report.json
 ````
 But I keep getting an error seemingly saying that the job is trying to access/write files outside its designated directory:
 ```
  Can't touch: cannot touch '/Project.tmp/gitlab_runner_env':Permission denied 
  ```

## Your Environment

- Operating System and version: Windows 11
- Output of 'bearer version': 
```Can't touch: cannot touch '/Project.tmp/gitlab_runner_env':Permission denied ```
bearer version: 1.47.0
sha: `Using docker image sha256:af4adf345a11b01f8287649491affb0916e32efa42fedc9a42a6f36a9d1f4fe6 for bearer/bearer with digest bearer/bearer@sha256:26a33a799b66258a402cd472b5cc5250b654d88374c1648f0620cfec1545060a`
