### ISSUE TITLE
Bearer Scan on GitLab CI not Detecting Sensitive Information

### ISSUE THREAD

**Issue by gal-dahan** [Bearer/bearer#1764]
I'm trying to use Bearer for static application security testing (SAST) in my GitLab CI pipeline. I have downloaded the rules from [bearer-rules](https://github.com/Bearer/bearer-rules) and am using them to scan for vulnerabilities, including sensitive data exposures like emails, credit card numbers, and passwords.
```
stages:
  - reports
bearer:
  stage: reports
  only:
    - main
  image: local-repo/bearer/bearer:1.49.0
  entrypoint: [ "" ]
  script:
    - echo "Starting Bearer scan..."
    - bearer scan src --disable-default-rules --debug --exit-code 0 --external-rule-dir=bearer-rules/rules --format gitlab-sast --output gl-sast-report.json
    - echo "Bearer scan completed."
    - echo "Contents of gl-sast-report.json:"
    - cat gl-sast-report.json
    - find /tmp -type f -name "*.jsonl" -exec cat {} \;

```
In my application code (Application.java), I have the following sensitive data:

```
String email = "example@gmail.com";
String creditCard = "4111-1111-1111-1111"; // Fake card for testing
String ssn = "123-45-6789"; // Example Social Security Number
String password = "123456"
System.out.println("User Email: " + email);
System.out.println("Credit Card: " + creditCard);
System.out.println("SSN: " + ssn);
System.out.println("Password : " + password);

```
Despite running the pipeline, the log shows that the file is being scanned, but no issues related to the email, creditCard, or password are detected. However, the gl-sast-report.json does show 3 vulnerabilities that are not related to these sensitive fields.

## Expected Behavior

Bearer should detect the sensitive data (email, credit card, password) and report them as vulnerabilities during the scan. These fields should be flagged in the scan results.

## Actual Behavior

The scan does not detect the sensitive fields (email, creditCard, password).
The vulnerabilities reported in the gl-sast-report.json do not correspond to these sensitive values.
The debug logs show the scan is running, but no issues are found related to the sensitive data in the code.

## Your Environment

- Operating System and version: gitlab 
- Output of 'bearer version':1.49.0
```
bearer version: 1.49.0
sha: xxx
```
