### ISSUE TITLE
Rework config file

### ISSUE THREAD

**Issue by cfabianski** [Bearer/bearer#281]
The current config file is becoming way too big. It contains `detectors` and `policies` and its content.
We need to keep this folder as slim as possible

Let's add external folders for detectors and policies 

**current**

```yaml
policy:
    only-policy: []
    skip-policy: []

report:
    format: ""
    output: ""
    report: policies

scan:
    context: ""
    debug: false
    disable-domain-resolution: true
    domain-resolution-timeout: 3s
    force: false
    internal-domains: []
    custom_detector: # <--- to be removed
      # Long content
    policies: # <--- to be removed
      # Long content
```

**after**

```yaml
policy:
    only-policy: []
    skip-policy: []

detector:
    only-detector: [] # <--- to add
    skip-detector: [] # <--- to add
  
report:
    format: ""
    output: ""
    report: policies

scan:
    context: ""
    debug: false
    disable-domain-resolution: true
    domain-resolution-timeout: 3s
    force: false
    internal-domains: []
    external-detector-dir: [] #  <--- to add
    external-policy-dir: [] # <--- to add
```
