### ISSUE TITLE
Build a docker image 

### ISSUE THREAD

**Issue by cfabianski** [Bearer/bearer#286]
Docker seems like an interesting option to help people get started with curio on any setup very easily.
In the end, it should be as simple as running `docker pull bearer/curio:latest`.

We should use a small image like `alpine` to run the binary 

**Links**
- https://goreleaser.com/customization/docker/?h=dockers
- https://github.com/aquasecurity/trivy/blob/main/goreleaser.yml#L98-L148

**Comment by cfabianski** [comment]
## Docker Compose

You can now write a docker-compose.yml file that looks like this

```yaml
version: "3"
services:
  curio:
    platform: linux/amd64
    image: bearer/curio:latest-amd64
    volumes:
      - /path/to/repo:/tmp/scan
```

You can then run 

```bash
docker compose run curio scan /tmp/scan --debug
```

## Docker

```bash
docker run --rm -v /path/to/repo:/tmp/scan bearer/curio:latest-amd64 scan /tmp/scan
```

Images are available on [Docker Hub](https://hub.docker.com/r/bearer/curio) or on [ghcr.io](https://github.com/Bearer/curio/pkgs/container/curio)
