### ISSUE TITLE
Improve external rule error messages

### ISSUE THREAD

**Issue by markmichon** [Bearer/bearer#545]
Currently, if there is a problem with the pattern for a custom rule you get the following error:
```json
{"level":"fatal","time":"2023-02-09T11:38:33-08:00","message":"Failed to start curio, error with your configuration custom detector error: failed to instantiate composition ruby:failed to create rule custom_rule_name: error compiling pattern: failed to build: error parsing pattern at 1:16: CurioVar1"}
exit status 1
```

Example pattern that triggered the error:
```
patterns:
  - pattern: |
      JWT.$<_>({$<DATA_TYPE>})
    filters:
      - variable: DATA_TYPE
        detection: datatype
```

While it does eventually mention that there's a problem compiling the pattern, it takes a bit to get there. Also, it looks to provide the location hint for the compiled pattern rather than the true location in the source file. 

Ideally, the error would:
- Omit information unrelated to it being a pattern parsing error (or at least prioritize the cause, rather than have it nested within all the problems it caused)
- use the yml file's line and column numbers
- use the yml files erroneous line instead of CurioVar1
- probably shouldn't be JSON output
