### ISSUE TITLE
Add relevant libraries to rule metadata

### ISSUE THREAD

**Issue by elsapet** [Bearer/bearer#639]
We should consider adding to the rule metadata a list of the libraries (gems, etc) included in the rule's patterns, so that it is easy to know which libraries are supported by the rule. 

Proposed structure: 

```yaml
metadata:
  ...
  libraries:
    - name: Some Library
      docs: https://www.docs.some-lib.com
      versions:
        - 1.0.0
        - 1.2.0
    - name: Another Library
      docs: https://www.docs.lib-anon.com
      versions:
        - 3.0.1
```
