### ISSUE TITLE
Auxiliary rules not matching on JS destructured assignment

### ISSUE THREAD

**Issue by elsapet** [Bearer/bearer#698]
## Description & Reproduction

There is destructured assignment in JavaScript: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

It is common to use auxiliary rules to catch assignment as well as the object itself (e.g. to catch both `x` and also `y` in the case where we have assigned `x` to `y` e.g. `y = x`). This does not recognise argument destructuring.

Consider the `javascript_express_external_resource` rule: 
```yaml
auxiliary:
  - id: javascript_express_external_resource_req_object
    patterns:
      - req.params
      - req.query
      - req.body
      - req.cookies
      - req.headers
```

The following code samples are equivalent however the rule matches only on the first sample: 

```javascript
// matches

    app.get("/tutorial/:page", (req, res) => {
        const page = req.params.page
        return res.render(`tutorial/${page}`, {
            environmentalScripts
        });
    });
```

```javascript
// does not match

    app.get("/tutorial/:page", (req, res) => {
        const {
            page
        } = req.params
        return res.render(`tutorial/${page}`, {
            environmentalScripts
        });
    });
```

## Repo steps:

1. Scan both of the above code samples
2. Rule `javascript_express_external_resource` only triggers for the first code sample, but we'd expect it to trigger on both samples

## Expected Behavior

The rule engine recognises destructured argument assignment

## Actual Behavior

The rule engine does not recognise destructured assignment

## Your Environment

- Operating System and version:
- Output of 'bearer version':
```
bearer version: 0.00.0
sha: xxx
```
