### ISSUE TITLE
Improve Trigger in rule to better deal with DataType

### ISSUE THREAD

**Issue by cfabianski** [Bearer/bearer#744]
We currently support 4 different types for `trigger` when writing a rule (`presence`, `absence`, `local` and `global`).

**current**

```yaml
# rule.yml
trigger: local | global | presence | absence
```

## History

We started with only 2 triggers `global` and `local`. So we were firing the rule when we had the patterns matching and we detected some data types either globally or locally.
We then introduced the new trigger `presence` to fire no matter if we had detected some data types or not.

The `presence` is very close to the `global` trigger (especially since we refactored the severity calculation), expect that a `presence` rule can fire even when there are no data types detected globally.

Later on, we introduced the `absence` trigger. This is when you have an auxiliary pattern that's matching but the whole global pattern doesn't. Again, that's not taking into account the data types.

In the end, it feels like we are mixing up 2 things:
- when do we trigger? (`absence` or `presence`)
- should we care about the data types at all? if so, locally or globally?

## Proposal

We could make it a bit easier to read by making the following changes

**proposal**

```yaml
trigger:
  pattern: present | absent # or missing instead of `absent`
  pattern_initializer: <name-of-auxiliary-rule> # would be used in conjunction with `absent` to indicate what is the minimal setup to fire the rule in case the pattern is missing. Replaces `trigger_rule_on_presence_of`
  data_types: global # or not present
```

The `local` use case could be deducted from the rule itself. If we have in the filters `data_types` as a detection we would consider the local scope
A missing `data_types` node, would indicate that we wouldn't take the data types into account to fire the rule. 

## References

- https://github.com/Bearer/bearer/pull/727
