### ISSUE TITLE
Severity calculation when local data type vs global data type

### ISSUE THREAD

**Issue by cfabianski** [Bearer/bearer#832]
## Description

Let's take those 2 snippets in an application processing Sensitive Personal Data:

```javascript
crypto.createHash('md5').update(data).digest('hex') // L1
crypto.createHash('md5').update(user.email).digest("hex") // L2
```

and this rule

```yaml
patterns:
  - pattern: |
      $<VAR>.update()
  - pattern: |
      $<VAR>.update($<DATA_TYPE>)
    filters:
      - variable: VAR
        detection: create_hash
      - variable: DATA_TYPE
        detection: datatype
auxiliary:
  - id: create_hash
    patterns:
      - pattern: |
          crypto.$<METHOD>($<ALGORITHM>$<...>)
        filters:
          - variable: METHOD
            values:
              - createHmac
              - createHash
          - variable: ALGORITHM
            values:
              - '"md5"'
              - '"sha1"'
```

We should trigger 2 failures, 1 for line 1 and 1 for line 2.
The Line 2 should trigger with Local Data Type while the Line 1 should trigger with Global Data Type.

That's already the case but, when using Global Data Type (in this case Sensitive Personal Data) we will add a lot of weight in the calculation of the severity. Local Data Type (in this case Personal Data) will have a lower weight.

We will then end up with 2 failures, 1 critical (line 1) and 1 medium (line 2)

## Expected Behaviour

We should have more weight for when the data type is found locally
