### ISSUE TITLE
Add support for optional datatype

### ISSUE THREAD

**Issue by vjerci** [Bearer/bearer#870]
## About the feature

At the moment,  when we want to detect both datatype and occurrence of pattern, we have a lot of similar patterns in the same rule.
This is a snippet from `ruby_weak_encryption rule`
```
  - pattern: |
      $<VAR>.$<METHOD>()
    filters:
      - variable: VAR
        detection: openssl_rsa_init
      - variable: METHOD
        values:
          - private_decrypt
          - private_encrypt
          - public_decrypt
          - public_encrypt
  - pattern: |
      $<VAR>.$<METHOD>($<DATA_TYPE>)
    filters:
      - variable: VAR
        detection: openssl_rsa_init
      - variable: METHOD
        values:
          - private_decrypt
          - private_encrypt
          - public_decrypt
          - public_encrypt
      - variable: DATA_TYPE
        detection: datatype
```

It would be ideal if we could somehow specify that datatype is optional. It would greatly reduce the amount of code we need for a rule. Perhaps a syntax could be something like `$<?><DATA_TYPE>` which would then, behind the scenes, compile to 2 rules, one with datatype extraction and one for presence.

**Comment by didroe** [comment]
You might be able to use an aux rule to do this. eg.

```yaml
  - id: ruby_weak_encryption_optional_datatype
    patterns:
      - $<_>
      - pattern: $<DATA_TYPE>
        filters:
          - variable: DATA_TYPE
            detection: datatype
```

**Comment by didroe** [comment]
Or actually, an `either` filter could be better:

```yaml
  - pattern: |
      $<VAR>.$<METHOD>($<OPT_DATA_TYPE>)
    filters:
      - variable: VAR
        detection: openssl_rsa_init
      - variable: METHOD
        values:
          - private_decrypt
          - private_encrypt
          - public_decrypt
          - public_encrypt
      - either:
        - variable: OPT_DATA_TYPE
          detection: datatype
        - not:
            variable: OPT_DATA_TYPE
            detection: datatype
```
