### ISSUE TITLE
Documentation for GitLab CI/CD integration

### ISSUE THREAD

**Issue by cfabianski** [Bearer/bearer#893]
We have a GitHub Action but it's also very easy to integrate with GitLab.
Adding this to your `.gitlab-ci.yml` will generate a similar output 

```yaml
image: 
  name: bearer/bearer
  entrypoint: [ "" ]

bearer:
  script: bearer scan .
```

~See [example](https://gitlab.com/cfabianski/bear-publishing/-/blob/e358932f91c3413d464952c1118080ae123e8253/.gitlab-ci.yml)~
[EDIT] See [this](https://gitlab.com/cfabianski/bear-publishing/-/blob/main/.gitlab-ci.yml) example instead 

https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#override-the-entrypoint-of-an-image
