### ISSUE TITLE
Improve pattern joining logic

### ISSUE THREAD

**Issue by didroe** [Bearer/bearer#973]
# Background

When one rule uses another rule (via a filter), and those rules contain variables with the same name, the AST nodes of those variables are unified. Meaning a match will only happen if both rules match with the same AST node for those variables.

When there are multiple results for a `detection` filter, any variables that aren't consistent (ie. have the same value) between the matches are ignored when joining variables to the parent pattern. In effect this means there is a single set of unified variables for the entire pattern. This approach was taken to make the implementation simpler, due to how filters were previously implemented.

# Proposal

Instead of having a single set of variables, we should consider all of the matches independently. A pattern would then return results for the filtered product of all of it's filters (all results from each filter joined on matching variables).

# Example

We have rules that follow a similar structure to this:

```yaml
patterns:
  - pattern: query($<USER_INPUT>)
    filters:
      - variable: USER_INPUT
        detection: user_input
      - not:
          variable: USER_INPUT
          detection: sanitized
auxiliary:
  - id: sanitized
    patterns:
      - pattern: sanitize($<SANITIZED_USER_INPUT>)
        filters:
          - variable: SANITIZED_USER_INPUT
            detection: user_input
  - id: user_input
    patterns:
      - pattern: $<MATCHED_USER_INPUT>
        filters:
          - variable: MATCHED_USER_INPUT
            detection: user_input_source
  - id: user_input_source
    patterns:
      - params
```

This relies on `MATCHED_USER_INPUT` being equated between the main pattern's user-input filter and the sanitized rule's filter. However, when there are multiple matches for user input, this variable will not be joined as the values will be inconsistent between the results. This leads to **not** detecting cases where at least one user-input is sanitized. eg:

```ruby
query(sanitize(params[:safe]) + params[:unsafe])
```
